version: '3'
services:
  fastapi_server1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_server1
    restart: always
    ports:
      - "8001:8000"
    networks:
      - fastapi_network

  fastapi_server2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_server2
    restart: always
    ports:
      - "8002:8000"
    networks:
      - fastapi_network

  nginx_load_balancer:
    image: nginx:latest
    container_name: nginx_load_balancer
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
